language: python
service: docker

jobs:
  include:
    - stage: test
      name: "Unit tests"
      python: 3.7
      os: linux
      install:
        - pip install -r requirements-dev.txt
      script: make test-full

    - stage: build
      name: "Distribute"
      python: 3.7
      os: linux
      if: branch = master
      script: make distribute
  
notifications:
  on_success: never
  on_failure: never